version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.8.4

    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn clean install -DskipTests

      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
