version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Setup Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: Build with Maven
          command: mvn clean install -DskipTests

      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
