version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: default
    steps:
      - checkout  # Check out your source code
      - setup-java:
          version: 11  # Set the desired Java version
      - run:
          name: Build and Test
          command: mvn clean test

workflows:
  version: 2
  build:
    jobs:
      - build
